apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ethminer
  labels:
    app: ethminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ethminer
  template:
    metadata:
      labels:
        app: ethminer
    spec:
      containers:
        - name: ethminer
          image: localhost:5000/eth:latest
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - /usr/local/bin/ethminer
              - --help
            initialDelaySeconds: 30
            periodSeconds: 60
          resources:
            limits:
              amd.com/gpu: 1
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
        searches:
          - ns1.svc.cluster.local

